INSERT INTO BOOK (`TITLE`) VALUES ('Voina i mir');
INSERT INTO AUTHOR (BOOK_ID, `FIO`) VALUES (1, 'L.N. Tolstoy');
INSERT INTO GENRE (BOOK_ID, `NAME`) VALUES (1, 'Epic novel');

-- INSERT INTO BOOK (`TITLE`) VALUES ('Voina i mir');
-- INSERT INTO AUTHOR (BOOK_ID, `FIO`) VALUES (1, 'L.N. Tolstoy');
-- INSERT INTO AUTHOR (BOOK_ID, `FIO`) VALUES (1, 'A.S. Pushkin');
-- INSERT INTO GENRE (BOOK_ID, `NAME`) VALUES (1, 'Epic');
-- INSERT INTO GENRE (BOOK_ID, `NAME`) VALUES (1, 'Novel');
--
-- INSERT INTO BOOK (`TITLE`) VALUES ('Galaxy in fire');
-- INSERT INTO AUTHOR (BOOK_ID, `FIO`) VALUES (2, 'L.N. Kukushkin');
-- INSERT INTO GENRE (BOOK_ID, `NAME`) VALUES (2, 'Novel');
-- INSERT INTO GENRE (BOOK_ID, `NAME`) VALUES (2, 'Fantastic');
-- INSERT INTO GENRE (BOOK_ID, `NAME`) VALUES (2, 'Comedy');