DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK(ID BIGINT AUTO_INCREMENT PRIMARY KEY, TITLE VARCHAR(255));
CREATE TABLE AUTHOR(ID BIGINT AUTO_INCREMENT PRIMARY KEY, BOOK_ID BIGINT, FIO VARCHAR(255));
CREATE TABLE GENRE(ID BIGINT AUTO_INCREMENT PRIMARY KEY, BOOK_ID BIGINT, NAME VARCHAR(255));

ALTER TABLE AUTHOR ADD CONSTRAINT FK_AUTHOR_ID FOREIGN KEY (BOOK_ID) references BOOK(id);
ALTER TABLE GENRE ADD CONSTRAINT FK_GENRE_ID FOREIGN KEY (BOOK_ID) references BOOK(id);

-- DROP TABLE IF EXISTS BOOK;
-- DROP TABLE IF EXISTS AUTHOR;
-- DROP TABLE IF EXISTS GENRE;
-- DROP TABLE IF EXISTS BOOK_AUTHOR;
-- DROP TABLE IF EXISTS BOOK_GENRE;
--
-- CREATE TABLE BOOK(ID BIGINT AUTO_INCREMENT PRIMARY KEY, TITLE VARCHAR(255));
-- CREATE TABLE AUTHOR(ID BIGINT AUTO_INCREMENT PRIMARY KEY, FIO VARCHAR(255));
-- CREATE TABLE GENRE(ID BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));
--
-- CREATE TABLE BOOK_AUTHOR(AUTHOR_ID BIGINT, BOOK_ID BIGINT, NAME VARCHAR(255));
-- CREATE TABLE BOOK_GENRE(GENRE_ID BIGINT, BOOK_ID BIGINT, NAME VARCHAR(255));
--
-- ALTER TABLE BOOK_AUTHOR ADD CONSTRAINT FK_AUTHOR_ID FOREIGN KEY (BOOK_ID) references BOOK(id);
-- ALTER TABLE BOOK_GENRE ADD CONSTRAINT FK_GENRE_ID FOREIGN KEY (BOOK_ID) references BOOK(id);