DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK(ID BIGINT AUTO_INCREMENT PRIMARY KEY, TITLE VARCHAR(255));
CREATE TABLE AUTHOR(ID BIGINT AUTO_INCREMENT PRIMARY KEY, BOOK_ID BIGINT, FIO VARCHAR(255));
CREATE TABLE GENRE(ID BIGINT AUTO_INCREMENT PRIMARY KEY, BOOK_ID BIGINT, NAME VARCHAR(255));

ALTER TABLE AUTHOR ADD CONSTRAINT FK_AUTHOR_ID FOREIGN KEY (BOOK_ID) references BOOK(id);
ALTER TABLE GENRE ADD CONSTRAINT FK_GENRE_ID FOREIGN KEY (BOOK_ID) references BOOK(id);