DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS BOOK;

CREATE TABLE AUTHOR(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIO VARCHAR(50));

CREATE TABLE GENRE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30));

CREATE TABLE BOOK(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_ID BIGINT REFERENCES AUTHOR(ID),
    GENRE_ID BIGINT REFERENCES GENRE(ID),
    TITLE VARCHAR(80));

CREATE TABLE COMMENT(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_ID BIGINT REFERENCES BOOK(ID) ON DELETE CASCADE,
    TEXT VARCHAR(255));